@startuml
[*] --> Активная
state Активная {
    [*] --> Обычная
    Обычная --> Премиум : Клиент стал премиум пользователем
    Премиум --> Обычная : Клиент стал обычным пользователем
    ||
    [*] --> Заблокированная : [Попытка мошенничества]
    ||
    [*] --> Просроченная : [Тайм-айт по истечению 3 лет]
    ||
    [*] --> Утерянная : [Карта найдена]
}
@enduml