@startuml
start
:Клиент регистрируется на сайте или входит существующий аккаунт;
:Система подтверждает учетные данные клиента;

:Клиент выбирает товары и добавляет их в корзину;
:Клиент переходит к оформлению заказа
:Клиент вводит промокод или система автоматически применяет скидку;
:Система проверяет условия использования скидки;
if (Промокод применен?) then (Нет)
    :Ошибка применения скидок;
    :Заказ расчитывается без скидки;
else (Да)
    :Обновление суммы заказа с учетом скидки;
endif    
:Клиент выбирает способ доставки и оплаты;
:Система проверяет наличие каждого товара в выбранных количествах;
fork
    :Клиент выбирает способ оплаты (кредитная карта, PayPal, банковский перевод и т.д.);
    :Система проверяет платежные детали и производит транзакцию;
fork again
    :Система уведомляет склад о необходимости собрать заказ;
    :Сотрудники склада комплектуют заказ по списку;
end fork
if (Платеж успешен и товар в наличии?) then (Да)
    :Система обновляет статус заказа по мере его продвижения к доставке;
    :Клиент получает уведомления о каждом изменении статуса;
    stop
else (Нет)
    :Уведомление клиента с причиной;
    if (Недостаточно средств?) then
        :Уведомление клиента с причиной;
        :Предложить другой способ оплаты;
    elseif (Неверные данные?) then
        :Уведомление клиента с причиной;
        :Попросить исправить данные;
    elseif (Платёжная система недоступна?) then
        :Уведомление клиента с причиной;
        :Сообщение о технической проблеме;
    elseif (Отсутствует товар?) then
        :Предложить выбрать товар из аналогичной категории;
        :Предоставить возможность оставить заказ в ожидании;
        :Автоматически информировать клиента о поступлении товара;
        stop
endif
:Предложение связаться с поддержкой;
if (Клиаента устраивает решение?) then (Да)
    :Клиент использует предложенное решение и возвращается в блок Оплаты;
    stop
else (Нет)
:Заказ отменяется;
:Клиенту возвращаются средства(если были списаны);
stop
@enduml